# Assignment 2 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os

#I have used all text files in files folder in this IRS_A. I have define some functions and working with them in this whole IRS_A.ipynb


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [2]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [3]:
#Your code starts here   
def countFiles():
    folder_path = './files' #files folder in current working directory.
    file_count = len(os.listdir(folder_path))
    return file_count

def dictionaryOfFiles():
    for file in os.listdir('./files'):
        if file.endswith('.txt'):
                key = file
                files_dict[key] = files_dict.get(key,0)+1 #if there is no value at that key default 0 will be set.
    return files_dict
#Your code ends here       

Displaying the count of files.

In [4]:
print("\nTotal Number  of files\n", countFiles())


Total Number  of files
 7


Displaying Dictionary containing all files.

In [5]:
print("\nDictionary containing  files\n", dictionaryOfFiles())


Dictionary containing  files
 {'f1.txt': 1, 'f2.txt': 1, 'f3.txt': 1, 'f4.txt': 1, 'f5.txt': 1, 'f6.txt': 1, 'synonyms.txt': 1}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [6]:
#Your code starts here  
def wordsInFiles():
      for file in os.listdir('./files'):
        if file.endswith('.txt'):
            file_path = os.path.join('./files', file) #ie complete path /files/f1.txt etc.
            with open(file_path,'r') as f:
                words = f.read().split() #creating list of words of each file may contain duplicate values
                for word in words:          #iterating words list to fetch each word
                    unique_word_set.add(word) #adding unique values to set
      return unique_word_set #uniquewordse contains 1 , and 1 : as they are dealt a separate word because of indentation in synonyms.txt file

print(f'Unique words in every file\n {wordsInFiles()} \n count of files {countFiles()}')



#Your code ends here

Unique words in every file
 {'society', 'instance', 'examine', 'Lahore', 'tome', 'Lahore.', 'sample', 'letter', 'dossier', 'my', 'bring', 'question', 'software', 'organization', 'best', 'the', 'forgotten', 'replacement', 'document', 'structure', 'obtain', 'machine', 'favorite', 'mislaid', 'amazing', 'system', 'author', 'at', 'draft', 'back', 'arrangement', 'read', 'interesting', 'am', 'Town', 'application', 'study', 'absorbing', 'missing', 'lost', ':', 'paper', 'platform', 'This', 'fascinating', 'features.', 'device', 'create', 'search', 'look', 'car', 'form', 'example', 'My', 'book', 'framework', 'illustration', 'Range', 'pen', 'publication', 'Hi', 'processor', 'I', 'for', 'file', 'demonstration', 'synonym', 'fetch', 'car.', 'record', 'Hassan', 'program', 'Rover', 'equivalent', 'write', 'fountain', 'retrieve', 'request', 'of', 'recover', 'app', 'ballpoint', 'report', ',', 'explore', 'inquiry', 'peruse', 'ink', 'best.', 'scan', 'volume', 'misplaced', 'novel', 'has', 'alternate', 'query

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

- Create Term doc matrix such that colmns will be unique words and all the files will be rows
- Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [7]:
#Your code starts here    
def termMatrix():
    files = countFiles()
    term_matrix = np.zeros([files,len(unique_word_set)]) # creating a table of size m*n filling each [i,j] with 0
    return term_matrix

def dictionaryOfUniqueWords():
    listOfUniqueWords = list(unique_word_set) #converting the following set to list so it can become iterateable
    uniqueWords = dict() #creating adictionary to store key-value pairs ie uniqueWords and their indexes
    for i in range(len(unique_word_set)):
        key = listOfUniqueWords[i]
        uniqueWords[key] = uniqueWords.get(key,0)+i #assigning dictionary uniqueWords, keys are words and indexes are their values
    return uniqueWords

def dictionaryOfFiles():
    i = 0
    fileDictionary = dict()
    for file in os.listdir('./files'):
        if file.endswith('.txt'):
            key = file
            fileDictionary[key] = fileDictionary.get(key,0)+i #assigning dictionary fileDictionary, keys are file name and indexes are their values.
            i = i+1
    return fileDictionary

    

print(termMatrix())
print(f'dictionary of unique words \n{dictionaryOfUniqueWords()}')
print(f'dictionary of files\n {dictionaryOfFiles()}')


#Your code ends here

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0.

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

- Fill the term doc matrix by checking if the unique word exists in a file or not
- If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
- Do the same for all the files present in the directory

In [8]:
#Your code starts here
def termDocMatrix(term_doc_matrix):
    for i in dictionaryOfFiles().keys():
        file_path =  os.path.join('./files', i) #ie complete path /files/f1.txt etc. 
        with open(file_path,'r') as f:
            for line in f: #iterating each line in each file
                words = line.split(' ')
                for word in words: #iterating each word in each line
                    if word in dictionaryOfUniqueWords().keys(): #matching word of file with the uniquewords
                        term_doc_matrix[dictionaryOfFiles().get(i),dictionaryOfUniqueWords().get(word)] = 1 
    return term_doc_matrix
print(f'Dictionary of unique words\n{dictionaryOfUniqueWords()}')
print(f'Term Document Matrix\n {termDocMatrix(termMatrix())}')
#Your code ends here

Dictionary of unique words
{'society': 0, 'instance': 1, 'examine': 2, 'Lahore': 3, 'tome': 4, 'Lahore.': 5, 'sample': 6, 'letter': 7, 'dossier': 8, 'my': 9, 'bring': 10, 'question': 11, 'software': 12, 'organization': 13, 'best': 14, 'the': 15, 'forgotten': 16, 'replacement': 17, 'document': 18, 'structure': 19, 'obtain': 20, 'machine': 21, 'favorite': 22, 'mislaid': 23, 'amazing': 24, 'system': 25, 'author': 26, 'at': 27, 'draft': 28, 'back': 29, 'arrangement': 30, 'read': 31, 'interesting': 32, 'am': 33, 'Town': 34, 'application': 35, 'study': 36, 'absorbing': 37, 'missing': 38, 'lost': 39, ':': 40, 'paper': 41, 'platform': 42, 'This': 43, 'fascinating': 44, 'features.': 45, 'device': 46, 'create': 47, 'search': 48, 'look': 49, 'car': 50, 'form': 51, 'example': 52, 'My': 53, 'book': 54, 'framework': 55, 'illustration': 56, 'Range': 57, 'pen': 58, 'publication': 59, 'Hi': 60, 'processor': 61, 'I': 62, 'for': 63, 'file': 64, 'demonstration': 65, 'synonym': 66, 'fetch': 67, 'car.': 68,

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [9]:
#Your code starts here  

colVector = np.zeros([len(unique_word_set),1]) #number of rows equals unique_word_set length, in this case we have only one col and multiple rows
print(f'colVector before query\n {colVector}')

#Your code ends here

colVector before query
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [10]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exists then increment the count of that word in word dictionary


In [11]:
#Your code starts here
for word in query.split():
    if word in unique_word_set:
        colVector[dictionaryOfUniqueWords().get(word),0] += 1
print(f'colVector after query\n {colVector}')
#Your code ends here

colVector after query
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [12]:
#Your code starts here  
resVector = np.dot(termDocMatrix(termMatrix()),colVector) #matrixMultiplication to get value against each file
print(f'result \n{resVector}')
print(f'max_index\n{np.argmax(resVector)}')
print(f'max\n{max(resVector)}')

#Your code ends here

result 
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]
max_index
4
max
[1.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [13]:
#Your code starts here

# making keys values and values keys so we can use index as key for particular file

fileDictionaryInterchanged = {value: key for key, value in dictionaryOfFiles().items()}
if(np.argmax(resVector)>0):  
    file = fileDictionaryInterchanged.get(np.argmax(resVector))
    print(file)
    file_path = os.path.join('./files', file)
    with open(file_path,'r') as f:
        print(f.read())
else:
    print("No such file with these words")




#Your code ends here

f5.txt
Bahria Town Lahore is the best society of Lahore. Lahore is the best.



Congratulations Now you are able to build your own small IRS.